.TH marvin 8 "February 04, 2016" "" "System Manager's Manual"
.SH NAME
\fBmarvin \fP- paranoia for normal people
.SH SYNOPSIS
.nf
.fam C
\fBmarvin\fP [\fB-d\fP] [\fB-h\fP] [\fB-s\fP]
.fam T
.fi
.SH DESCRIPTION
The Marvelous Marvin!
.PP
You can find the source code on GitHub:
.PP
.nf
.fam C
    https://github.com/hamishcunningham/pi-tronics/tree/master/marvin

.fam T
.fi
For more details see http://pi.gate.ac.uk/
.SH OPTIONS
.TP
.B
\fB-d\fP
Turn on debug mode.
.TP
.B
\fB-h\fP
The option \fB-h\fP displays help.
.SH EXAMPLE
$ \fBmarvin\fP
.SH SEE ALSO
\fBservice\fP(8)
.SH BUGS
Almost certainly!
.SH AUTHOR
Hamish Cunningham <http://pi.gate.ac.uk/>
