#!/bin/bash
#
# blinkip -- blink my IP
#
# Author: Hamish Cunningham <hamish@gate.ac.uk>
# This code is copyright Hamish Cunningham and the University of Sheffield
# and is licenced under GPL 3 or any later version.
#
### BEGIN INIT INFO
# Provides:          blinkip
# Short-Description: BlinkIP: blink my IP daemon
# Description:       This script is implements the daemon for
#                    BlinkIP (blink my IP)
### END INIT INFO

# standard locals
P="$0"
USAGE="`basename ${P}` [-h(elp)] [-d(ebug)] [-n(o blink)]"
OPTIONSTRING=hdn

# define LSB log_* functions.
. /lib/lsb/init-functions

# message & exit if exit num present
usage() { log_failure_msg Usage: $USAGE; [ ! -z "$1" ] && exit $1; }

# defaults
PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
DESC="BlinkIP: blink my IP daemon"
NAME=blinkip
DAEMON=/usr/sbin/$NAME
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

# options defaults
DEBUG=off
BLINK=on

# process options
[ ! -z "$*" ] && log_daemon_msg ${NAME} options: $*
while getopts $OPTIONSTRING OPTION
do
  case $OPTION in
    h)	usage 1 ;;
    d)	DEBUG=on ;;
    n)	BLINK=off ;;
    *)	usage 2 ;;
  esac
done 
shift `expr $OPTIND - 1`

# read configuration variable file if it is present
if [ -r /etc/default/$NAME ] 
then
  . /etc/default/$NAME
else
  logger "$0: no config data found - fatal error"
  exit 1
fi

# pretty date/time function
pdate() { date +%b-%d-%Y-%T; }

# tell the world
logger "=========== $0: running at `pdate` ==========="

# do the work; i and j index loop iterations for e.g. logging
i=0; j=0
while :
do
  i=`expr ${i} + 1`
  j=`expr ${j} + 1`

  # write IP to file; routine log message
  [ ${j} -eq ${LOG_INTERVAL} ] && {
    logger "${NAME}: blink is ${BLINK} at `pdate` (i=${i})" && j=0
    echo -e "${NAME}: network data at `pdate`:\n" >${IP_FILE}
    ifconfig >>${IP_FILE}
  }

  # take a break
  sleep ${MONITOR_FREQUENCY}
done &

# create PIDFILE
echo $! >${PIDFILE}
