#!/usr/bin/env python
import sys
import mopiapi
import errno

# This is the development version

VERSION=0.2
# for mopi firmware v3.03

#commands = ['-fv', '-i', '-rc', '-rc1', '-rc2', '-rpon', '-rs', '-s', '-sn', '-sv', '-v', '-v1', '-v2', '-wc', '-wc1', '-wc2', '-wpon', '-ws']
commands =   ['-i', '-fv', '-sn', '-h', '-s', '-sv', '-v', '-v1', '-v2', \
	'-rc', '-rc1', '-rc2', '-rpon', '-rs', '-wc', '-wc1', '-wc2', '-wpon', '-ws']
parameters = [   1,     0,     0,    0,    0,     0,    0,     0,     0, \
	    0,      0,      0,       0,     0,     3,      3,       3,      1,     1]


def shorthelp():
	print "Usage: mopicli [-h] [options]"
	print "Version %0.1f, API %0.1f" % (VERSION, mopiapi.getApiVersion())
	print "This is the development version"

def help():
	print "Miscellaneous:"
	print "  -i          I2C bus (default: %i)" % mopiapi.guessI2C()
	print "  -fv         Firmware version"
	print "  -sn         Serial number"
	print "  -h          Display this message"
	print ""
	print "Status:"
	print "  -s          MoPi status word"
	print "  -sv         Verbose status"
	print "  -v          Current battery voltage in mV"
	print "  -v1/-v2     Battery #1/#2 voltage in mV"
	print ""
	print "Read configuration options:"
	print "  -rc         Combined battery #1 and #2 configuration"
	print "  -rc1/-rc2   Configuration of battery #1/#2"
	print "  -rpon       Power on delay"
	print "  -rs         Shutdown delay"
	print ""
	print "Write configuration options:"
	print "  -wc mV mV mV         Combined battery #1 and #2 configuration"
	print "  -wc1/-wc2 mV mV mV   Configuration of battery #1/#2"
	print "  -wpon seconds        Power on delay seconds"
	print "  -ws seconds          Shutdown delay seconds"
	print ""
	print "All options may be used simultaneously. When doing so, they execute in the"
	print "  order they are listed in in this help message. However, only one of each may"
	print "  be used."

# read integer inputs to command c, with expected number of inputs
# if none are expected and there are some though, no biggy
def readInts(c, expected):
	ci = sys.argv.index(c) + 1
	data = []
	while ci < len(sys.argv):
		try:
			data.append(int(sys.argv[ci]))
		except:
			break
#		sys.argv.pop(ci)
		ci += 1
	if expected > 0 and len(data) != expected:
		print "mopicli. Bad input for " + c + "."
		sys.exit(1)
	return data

if len(sys.argv) == 1:
	shorthelp()
	sys.exit(0)

if '-h' in sys.argv:
	shorthelp()
	print ""
	help()
	sys.exit(0)

sys.argv.pop(0) # remove calling name...
# check that all the commands given are valid
for arg in sys.argv:
	if not arg.isdigit() and not arg in commands:
		print "mopicli. Unknown option: " + arg
		sys.exit(1)

status = 0
try:
	if '-i' not in sys.argv:
		mymopi = mopiapi.mopiapi()

	for ind,arg in enumerate(commands):
		if arg in sys.argv:
			par = readInts(arg, parameters[ind])

			if '-i' == arg:
				mymopi = mopiapi.mopiapi(par[0])

			if '-fv' == arg:
				data = mymopi.getFirmwareVersion()
				print '%i.%02i' % (data[0], data[1])

			if '-sn' == arg:
				print mymopi.getSerialNumber()


			if '-s' == arg:
				status = mopiapi.status(mymopi.getStatus())
				print status.getByte()

			if '-sv' == arg:
				if status == 0:
					status = mopiapi.status(mymopi.getStatus())
				print status.StatusDetail()

			if '-v' == arg:
				print mymopi.getVoltage()
			if '-v1' == arg:
				print mymopi.getVoltage(1)
			if '-v2' == arg:
				print mymopi.getVoltage(2)


			if '-rc' == arg:
				print ' '.join(map(str, mymopi.readConfig()))
			if '-rc1' == arg:
				print ' '.join(map(str, mymopi.readConfig(1)))
			if '-rc2' == arg:
				print ' '.join(map(str, mymopi.readConfig(2)))

			if '-rpon' == arg:
				print mymopi.getPowerOnDelay()

			if '-rs' == arg:
				print mymopi.getShutdownDelay()


			if '-wc' == arg:
				mymopi.writeConfig(par)
			if '-wc1' == arg:
				mymopi.writeConfig(par, 1)
			if '-wc2' == arg:
				mymopi.writeConfig(par, 2)

			if '-wpon' == arg:
				mymopi.setPowerOnDelay(par[0])

			if '-ws' == arg:
				mymopi.setShutdownDelay(par[0])

except IOError as e:
	if e.errno == errno.EACCES:
		print "mopicli. Permission denied." # add something about i2c bus
	elif e.errno == errno.EIO:
		print "mopicli. Communication error. Check bus? Check connection?"
	elif e.errno == errno.ECOMM:
		print "mopicli. Failed to write configuration."
		sys.exit(2)
	else:
		print "mopicli. " + e.strerror
	sys.exit(1)
except OSError as e:
	print "mopicli. " + e.strerror
	sys.exit(1)
except Exception as e:
	print "mopicli. " + str(e)
	sys.exit(1)
