#!/usr/bin/env bash
#
# simbamon -- a simple battery monitor
#
# Author: Hamish Cunningham <hamish@gate.ac.uk>
# This code is copyright Hamish Cunningham and the University of Sheffield
# and is licenced under GPL 3 or any later version.
#
### BEGIN INIT INFO
# Provides:          simbamon
# Short-Description: SimBaMon: a simple battery monitor daemon
# Description:       This script is implements the daemon for
#                    SimBaMon (a simple battery monitor)
### END INIT INFO

# Defaults
PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
DESC="SimBaMon: a simple battery monitor daemon"
NAME=simbamon
DAEMON=/usr/sbin/$NAME
DAEMON_ARGS=""
#DAEMON_ARGS="--options args"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
LMESS='battery level'
SHUTDOWN=shutdown

# Read configuration variable file if it is present
if [ -r /etc/default/$NAME ] 
then
  . /etc/default/$NAME
else
  logger "$0: no config data found - fatal error"
  exit 1
fi

# Pretty date/time function
pdate() { date +%b-%d-%Y-%T; }

# Tell the world
logger "=========== $0: running at `pdate` ==========="
logger "${NAME}: monitor frequency is ${MONITOR_FREQUENCY} seconds"

# Check for gpio command (which may be a function defined in config)
GPIO=
if [ "`type -t gpio`" = "function" ]
then
  GPIO=gpio
else
  GPIO=`which gpio`
fi
if [ -z "${GPIO}" ]
then
  echo   "${NAME}: cannot find gpio command: failing" >&2
  logger "${NAME}: cannot find gpio command: failing"
  exit 1
fi

# Put the relevant pins into read mode
gpio mode $IO_A in
gpio mode $IO_B in
gpio mode $IO_C in

# Current level; -1 means unset
BAT_LEVEL=-1

# Do the work; i and j index loop iterations for e.g. logging
i=0; j=0
while :
do
  i=`expr ${i} + 1`
  j=`expr ${j} + 1`

  # check the level and act if necessary
  BAT_LEVEL_BASE2=`gpio read ${IO_A}``gpio read ${IO_B}``gpio read ${IO_C}`
  BAT_LEVEL=`echo "ibase=2;${BAT_LEVEL_BASE2}" |bc`
  [ $BAT_LEVEL -le $BAT_WARNING ] && \
    logger "${NAME}: ${LMESS} is at or below warning level (${BAT_LEVEL})"
  if   [ $BAT_LEVEL -eq $POWER_OFF ]
  then
    wall <<< "${NAME}: power off requested: shutting down now!"
    logger "${NAME}: shutting down (POWER_OFF)"
    $SHUTDOWN -h now
  elif [ $BAT_LEVEL -eq $BAT_SHUTDOWN ]
  then
    wall <<< "${NAME}: battery empty: shutting down now!!!"
    logger "${NAME}: shutting down (BAT_SHUTDOWN)"
    $SHUTDOWN -h now
  elif [ $BAT_LEVEL -eq $BAT_CRITICAL ]
  then
    wall <<< \
      "${NAME}: ${LMESS} critical! shutting down in ${SHUT_DELAY} seconds!"
    logger "${NAME}: shutting down (BAT_CRITICAL, SHUT_DELAY=${SHUT_DELAY})"
    sleep $SHUT_DELAY
    $SHUTDOWN -h now
  elif [ $BAT_LEVEL -eq $BAT_WARNING ]
  then
    wall <<< "${NAME}: ${LMESS} is low! connect new battery or shut down"
    logger "${NAME}: BAT_WARNING; sleeping ${WARNING_INTERVAL}..."
    sleep $WARNING_INTERVAL
  fi

  # routine log messages
  [ ${j} -eq ${LOG_INTERVAL} ] && \
    logger "${NAME}: ${LMESS} is ${BAT_LEVEL} at `pdate` (i=${i})" && j=0

  # take a break
  sleep ${MONITOR_FREQUENCY}
done &

# Create PIDFILE
echo $! >${PIDFILE}
