#!/usr/bin/env bash
#
# simbamon -- a simple battery monitor
#
# Author: Hamish Cunningham <hamish@gate.ac.uk>
# This code is copyright Hamish Cunningham and the University of Sheffield
# and is licenced under GPL 3 or any later version.
#
### BEGIN INIT INFO
# Provides:          simbamon
# Short-Description: SimBaMon: a simple battery monitor daemon
# Description:       This script is implements the daemon for
#                    SimBaMon (a simple battery monitor)
### END INIT INFO

# Defaults
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="SimBaMon: a simple battery monitor daemon"
NAME=simbamon
DAEMON=/usr/sbin/$NAME
DAEMON_ARGS=""
#DAEMON_ARGS="--options args"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Pretty date/time function
pdate() { date +%b-%d-%Y-%T; }

# Tell the world
logger "$0: running at `pdate`"
logger "${NAME}: monitor frequency is ${MONITOR_FREQUENCY} seconds"

# Current level; -1 means unset
BAT_LEVEL=-1

# Do the work; i and j index loop iterations for e.g. logging
i=0; j=0
while :
do
  i=`expr ${i} + 1`
  j=`expr ${j} + 1`

  # check the level
  # TODO

  # routine log messages
  [ ${j} -eq ${LOG_INTERVAL} ] && \
    logger "${NAME}: battery level is ${BAT_LEVEL} at `pdate` (i=${i})" && j=0

  # take a break
  sleep ${MONITOR_FREQUENCY}
done &

# Create PIDFILE
echo $! >${PIDFILE}
