Document: simbamon
Title: Debian simbamon Manual
Author: <insert document author here>
Abstract: This manual describes what simbamon is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/simbamon/simbamon.sgml.gz

Format: postscript
Files: /usr/share/doc/simbamon/simbamon.ps.gz

Format: text
Files: /usr/share/doc/simbamon/simbamon.text.gz

Format: HTML
Index: /usr/share/doc/simbamon/html/index.html
Files: /usr/share/doc/simbamon/html/*.html
