#!/bin/bash
#
# pibrush -- a simple paint brush
#
# Author: Hamish Cunningham <hamish@gate.ac.uk>
# Author: Fred Sonnenwald
# This code is copyright Hamish Cunningham and the University of Sheffield
# and is licenced under GPL 3 or any later version.
#
### BEGIN INIT INFO
# Provides:          pibrush
# Short-Description: PiBrush: a simple paint brush daemon
# Description:       This script is implements the daemon for
#                    PiBrush (a simple paint brush)
### END INIT INFO

# debug:
#exec &>/tmp/pibrush-log.txt

# standard locals
P="$0"
USAGE="`basename ${P}` [-s(erver)] [-c(lient)]"
OPTIONSTRING=hdcs

# define LSB log_* functions.
. /lib/lsb/init-functions

# message & exit if exit num present
usage() { log_failure_msg Usage: $USAGE; [ ! -z "$1" ] && exit $1; }

# defaults
PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/opt/pibrush
DESC="PiBrush: a simple paint brush daemon"
NAME=pibrush
DNAME=pibrushd
DAEMON=/usr/bin/$NAME
PIDFILE=/var/run/$DNAME.pid

# read configuration variable file if it is present
if [ -r /etc/default/$DNAME ]
then
  . /etc/default/$DNAME
else
  logger "${NAME}: no config data found - fatal error"
  exit 1
fi

# process options, this overrides the config file
ARGS="$*"
while getopts $OPTIONSTRING OPTION
do
  case $OPTION in
    h)	usage 1 ;;
    s)	MODE="server" ;;
    c)	MODE="client" ;;
    *)	usage 2 ;;
  esac
done 
shift `expr $OPTIND - 1`

# log the options we got
[ ! -z "${ARGS}" ] && log_daemon_msg "${NAME} options: ${ARGS}"

# pretty date/time function
pdate() { date "+%Y-%m-%d-%T" | sed 's,:,,g'; }


# switch which python script we execute depending on $MODE...
if [ "$MODE" == "server" ]
then
    SCRIPT="accel_server.py"
elif [ "$MODE" == "client" ]
    SCRIPT="accel_client.py"
else
  MSG="\$MODE not specified!"
  log_failure_msg "${NAME}: ${MSG}" >&2
  logger          "${NAME}: ${MSG}"
  exit 1
fi

# tell the world
logger "=========== ${NAME}: running at `pdate` ==========="

python $SCRIPT
