.TH mopi 8 "May 01, 2014" "" "System Manager's Manual"
.SH NAME
\fBmopi mopicli mopiapi.py \fP- MoPi configuration script, command-line interface,
\fBand Python API
.SH SYNOPSIS
.nf
.fam C
\fBmopi\fP [\fB-d\fP] [\fB-h\fP]
\fBmopicli\fP [ \fIoptions\fP ]
.fam T
.fi
.SH DESCRIPTION
Configuration and access tools for the MoPi mobile and 24/7 power board for
the Raspberry Pi:
.IP \(bu 3
\fBmopi\fP is for interactive configuration of e.g. battery types
.IP \(bu 3
mopiapi.py is a Python API that talks to the MoPi board over the I2C bus
.IP \(bu 3
\fBmopicli\fP is a command-line interface to the API (and is used by \fBmopi\fP to
communicate with the board)
.PP
You can find the source code on GitHub:
.PP
.nf
.fam C
    https://github.com/hamishcunningham/pi-tronics/tree/master/simbamon

.fam T
.fi
Part of the SimBaMon battery monitor package.
.PP
For more details see http://pi.gate.ac.uk/\fBmopi\fP
.SH OPTIONS
.TP
.B
\fB-d\fP
Turn on debug mode.
.TP
.B
\fB-h\fP
Display a help message.
.SH EXAMPLE
$ \fBmopi\fP
.SH SEE ALSO
simbamond
.SH BUGS
Almost certainly!
.SH AUTHOR
Hamish Cunningham <http://hamish.gate.ac.uk/>, Fred Sonnenwald
