.TH mopi 8 "April 30, 2014" "" "System Manager's Manual"
.SH NAME
\fBmopi \fP- MoPi configuration script
.SH SYNOPSIS
.nf
.fam C
\fBmopi\fP [\fB-d\fP] [\fB-h\fP]
.fam T
.fi
.SH DESCRIPTION
Configuration tool for the MoPi mobile and 24/7 power board
for the Raspberry Pi. You can find the source code on GitHub:
.PP
.nf
.fam C
    https://github.com/hamishcunningham/pi-tronics/tree/master/simbamon

.fam T
.fi
Part of the SimBaMon battery monitor package.
.PP
For more details see http://pi.gate.ac.uk/\fBmopi\fP
.SH OPTIONS
.TP
.B
\fB-d\fP
Turn on debug mode.
.TP
.B
\fB-h\fP
The option \fB-h\fP displays help.
.SH EXAMPLE
$ \fBmopi\fP
.SH SEE ALSO
.SH BUGS
Almost certainly!
.SH AUTHOR
Hamish Cunningham <http://hamish.gate.ac.uk/>
