.SH NAME
\fBmopi \fP- MoPi configuration tool
.SH SYNOPSIS
.nf
.fam C
\fBmopi\fP [\fB-d\fP] [\fB-h\fP] [\fB-v\fP] [\fB-l\fP]
.fam T
.fi
.SH DESCRIPTION
Easy user configuration tool for the MoPi mobile and 24/7 power board for
the Raspberry Pi.
.PP
Features\.\.\.
.RS
.IP \(bu 3
interactive configuration of e.g. battery types
.IP \(bu 3
view status
.IP \(bu 3
check relevant logs for errors
.RE
.PP
You can find the source code on GitHub:
.PP
.nf
.fam C
    https://github.com/hamishcunningham/pi-tronics/tree/master/simbamon

.fam T
.fi
Part of the SimBaMon battery monitor package.
.PP
For more details see http://pi.gate.ac.uk/\fBmopi\fP
.SH OPTIONS
.TP
.B
\fB-d\fP
Turn on debug mode.
.TP
.B
\fB-h\fP
Display a help message.
.TP
.B
\fB-v\fP
Display the version number.
.TP
.B
\fB-l\fP
Show recent log entries.
.SH EXAMPLE
$ \fBmopi\fP
.SH SEE ALSO
\fBmopicli\fP(8) \fBsimbamond\fP(8)
.SH BUGS
Almost certainly!
.SH AUTHOR
Hamish Cunningham <http://hamish.gate.ac.uk/>, Fred Sonnenwald
