.TH simbamon 8 "May 30, 2014" "" "System Manager's Manual"
.SH NAME
\fBsimbamon \fP- a Simple Battery Monitor daemon
.SH SYNOPSIS
.nf
.fam C
\fBsimbamon\fP [\fB-d\fP] [\fB-h\fP] [\fB-s\fP]
\fBservice\fP \fIsimbamond\fP [{start [\fB-d\fP][\fB-h\fP][\fB-s\fP]|stop|status|restart [\fB-d\fP][\fB-h\fP][\fB-s\fP]}]
.fam T
.fi
.SH DESCRIPTION
Battery monitoring for the Raspberry Pi\.\.\.
.PP
simbamon is an open source Linux daemon for
.RS
.IP \(bu 3
monitoring battery levels
.IP \(bu 3
sending warning messages to the user if the battery is low
.IP \(bu 3
shutting down cleanly at critical battery levels
.IP \(bu 3
managing a power supply on/off switch
.IP \(bu 3
writing relevant data to the system logs
.RE
.PP
You can find the source code on GitHub:
.PP
.nf
.fam C
    https://github.com/hamishcunningham/pi-tronics/tree/master/simbamon

.fam T
.fi
The core of the daemon is defined in three files:
.RS
.IP \(bu 3
/etc/default/\fIsimbamond\fP - configuration data
.IP \(bu 3
/usr/sbin/\fBsimbamon\fP - the daemon itself
.IP \(bu 3
/etc/init.d/\fIsimbamond\fP - an interface to the init subsystem that
Linux uses to manage daemons (amongst other things)
.RE
.PP
The last of these, \fIsimbamond\fP, is used by the operating system to start and
stop simbamon at boot or shutdown time, and can be used to control the daemon
manually when required. For example this command will stop the daemon:
.PP
.nf
.fam C
    sudo service simbamon stop

.fam T
.fi
The mopi utility is provided for easy user configuration.
.PP
For more details see http://pi.gate.ac.uk/pages/mopi.html#\fBsimbamon\fP
.SH OPTIONS
.TP
.B
\fB-d\fP
Turn on debug mode.
.TP
.B
\fB-h\fP
The option \fB-h\fP displays help.
.SH EXAMPLE
Restart the daemon with debugging on:
.PP
.nf
.fam C
    $ sudo service simbamond restart -d
.fam T
.fi
.SH SEE ALSO
\fBmopi\fP(8) \fBmopicli\fP(8) \fBservice\fP(8)
.SH BUGS
Almost certainly!
.SH AUTHOR
Hamish Cunningham <http://pi.gate.ac.uk/>
